<a href="https://colab.research.google.com/github/eloahbaracho/boson-matplotlib/blob/main/csv_datas_temperaturas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
#Criação de matriz com números aleatórios
print('Criação de matriz 3x3 com números aleatórios')
print(np.eye(3, 3, 3))

Criação de matriz 3x3 com números aleatórios
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
pip install pandas

In [9]:
import pandas as pd
#leitura de dados
df = pd.read_csv ("https://pycourse.s3.amazonaws.com/temperature.csv")
#visualizando as primeiras 3 linhas
df.head(3)

date  temperatura classification
0  2020-01-01         29.1         quente
1  2020-02-01         31.2   muito quente
2  2020-03-01         28.5         quente

In [10]:
#tipos de dados
df.dtypes

date               object
temperatura       float64
classification     object
dtype: object

In [17]:
#transformando o tipo da coluna date (object) para datetime
df['date'] = pd.to_datetime(df['date'])
df.dtypes


date              datetime64[ns]
temperatura              float64
classification            object
dtype: object

In [18]:
#setando o indice
df = df.set_index('date')
print(df.index)

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01'],
              dtype='datetime64[ns]', name='date', freq=None)


In [20]:
df.describe()

temperatura
count     6.000000
mean     26.800000
std       4.075782
min      20.000000
25%      25.000000
50%      28.250000
75%      28.950000
max      31.200000

from matplotlib import pyplot as plt
_df_0['temperatura'].plot(kind='hist', bins=20, title='temperatura')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['temperatura'].plot(kind='line', figsize=(8, 4), title='temperatura')
plt.gca().spines[['top', 'right']].set_visible(False)

In [22]:
#indexação por nome
#selecionando todas as linhas e coluna 1
df.loc[:, 'temperatura']

date
2020-01-01    29.1
2020-02-01    31.2
2020-03-01    28.5
2020-04-01    28.0
2020-05-01    24.0
2020-06-01    20.0
Name: temperatura, dtype: float64

In [23]:
#ordenando por uma coluna
df.sort_values(by='temperatura')

temperatura classification
date                                  
2020-06-01         20.0           frio
2020-05-01         24.0    confortavel
2020-04-01         28.0         quente
2020-03-01         28.5         quente
2020-01-01         29.1         quente
2020-02-01         31.2   muito quente

In [21]:
#indexação por índice
#Selecionando todas as linhas e a coluna 1
df.iloc[:,1]

date
2020-01-01          quente
2020-02-01    muito quente
2020-03-01          quente
2020-04-01          quente
2020-05-01     confortavel
2020-06-01            frio
Name: classification, dtype: object